### ISSUE TITLE
The raft node will never replay the log after restart if it cannot becomes leader or follower

### ISSUE THREAD

**Issue by pdu** [brpc/braft#64]
The process to reproduce the issue:

1. Have 2 nodes in the raft group
2. Insert 10 lines of data
3. Make snapshot
4. Insert 10 lines of data again
5. Shutdown both of the 2 nodes
6. Only start 1 node, and this node will only install the snapshot but not the log

It's quite easy to cause this case if you deploy the raft groups in k8s statefulset and also using AWS spot instances because of the network isolation.

The wanted behavior is:

1. The node can replay the log after installing the snapshot standalone
2. I've checked the logic in the code, the log replay will be trigger by either **LeaderStableClosure** or **FollowerStableClosure**. After all, it still replays the local log

I've hacked a quick fix which can pass the above use case, but I am not sure if it will cause other side effects. Please help to check about the code here at https://github.com/pdu/braft/blob/master/src/braft/node.cpp#L482

**Comment by chenzhangyi** [comment]
Currently the node cannot determine which log is committed until it gets enough information from the cluster. Replaying the log stand along might break the consensus since the local log might contain uncommitted data. 

In this case it demands all the nodes are alive since quorum of 2 is 2 exactly. In the scenarios where restrict consistency is acquired,  operators or the deploying systems have to make efforts to guarantee that at least quorum of the nodes are alive.

If weak consistency is acceptable, checkpoints which contains enough information can be periodically appended to the storage may help the node replay most of the committed log after restarting without any communication. 

We had discussed this kind of solution at the very beginning when we designed braft and we refused to do so. I still doubt that if it could make sense in real production env since it's very rare that quorum of nodes are unavailable and the implementation brings more iops on the storage and makes the code more complex.

**Comment by chenzhangyi** [comment]
I think the problem in this case is not about the rolling update.  It's that there's only 2 nodes and that either of the 2 is unavailable will make the group unavailable. If you make create a group of 3 nodes, maybe it is not a issue then.

**Comment by chenzhangyi** [comment]
I think the problem in this case is not about the rolling update.  It's that there's only 2 nodes and that either of the 2 is unavailable will make the group unavailable. If you create a group of 3 nodes, maybe it is not a issue then.

**Comment by demiaowu** [comment]
there is no quorum, raft node cannot start for servicing. When the new leader start, it must through commit a noop log entry to implicit commit the previous log which don't known whether have been committed. In braft, it through flush configuration to implement the same effect.
